development:
  adapter: redis
  url: redis://localhost:6379/1

# test:
#   adapter: async

production:
  adapter: redis
local: &local
  :url: <% ENV['REDIS_URL'] %>
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local
