# config/redis/cable.yml
local: &local
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
development: *local
test: *local
production: &production
  :url: <%= ENV["REDIS_URL"] %>
  :host: <%= URI.parse(ENV["REDIS_URL"]).host %>
  :port: <%= URI.parse(ENV["REDIS_URL"]).port %>
  :password: <%= URI.parse(ENV["REDIS_URL"]).port %>
  :inline: true
  :timeout: 1
